spring:
  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?userUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: root
    # 连接超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数,默认8
        max-active: 200
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000ms

# Mybatis-plus配置
mybatis-plus:
  # Mapper.xml路径
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 别名
  type-aliases-package: com.chc.seckill.entity


# Mybatis SQL日志
logging:
  level:
    com.chc.seckill.mapper: debug